question_data = [
    {"question": 'An episode of "The Simpsons" is dedicated to Moe Szyslak\'s bar rag.', "correct_answer": "True"},
    {"question": 'The Angry Video Game Nerd\'s alter ego is "Board James".', "correct_answer": "True"},
    {"question": 'Watch_Dogs 2 is a prequel.', "correct_answer": "False"},
    {"question": 'The PlayStation was originally a joint project between Sega and Sony that was a Sega Genesis with a disc drive.', "correct_answer": "False"},
    {"question": "E = MC3", "correct_answer": "False"},
    {"question": "According to Greek Mythology, Zeus can control lightning.", "correct_answer": "True"},
    {"question": "The Windows 7 operating system has six main editions.", "correct_answer": "True"},
    {"question": 'In the game "Melty Blood Actress Again Current Code", you can enter Blood Heat mode in Half Moon style.', "correct_answer": "False"},
    {"question": "Pac-Man was invented by the designer Toru Iwatani while he was eating pizza.", "correct_answer": "True"},
    {"question": "TF2: Sentry rocket damage falloff is calculated based on the distance between the sentry and the enemy, not the engineer and the enemy.", "correct_answer": "False"},
    {"question": "Pointers were not used in the original C programming language; they were added later on in C++.", "correct_answer": "False"},
    {"question": "Deadpool's identity is Slade Wilson.", "correct_answer": "False"},
    {"question": "It's not possible to format a write-protected DVD-R Hard Disk.", "correct_answer": "True"},
    {"question": "Ashley Frangipane performs under the stage name Halsey.", "correct_answer": "True"},
    {"question": 'Leonardo DiCaprio won an Oscar for Best Actor in 2004\'s "The Aviator".', "correct_answer": "False"},
    {"question": "Microphones can be used not only to pick up sound, but also to project sound similar to a speaker.", "correct_answer": "True"},
    {"question": "Toronto is the capital city of the North American country of Canada.", "correct_answer": "False"},
    {"question": "In 2016, the United Kingdom voted to stay in the EU.", "correct_answer": "False"},
    {"question": "The Klingon home planet is Qo'noS.", "correct_answer": "True"},
    {"question": 'In the Season One Championship of "League of Legends", the highest achievable rank was Diamond.', "correct_answer": "False"},
    {"question": "The Olympics tennis court is a giant green screen.", "correct_answer": "True"},
    {"question": "In Topology, the complement of an open set is a closed set.", "correct_answer": "True"},
    {"question": 'The 2005 video game "Call of Duty 2: Big Red One" is not available on PC.', "correct_answer": "True"},
    {"question": "Centripedal force is an apparent force that acts outward on a body moving around a center, arising from the body's inertia.", "correct_answer": "False"},
    {"question": "Joko Widodo has appeared in the cover of a TIME magazine.", "correct_answer": "True"},
    {"question": 'The 2010 film "The Social Network" is a biographical drama film about MySpace founder Tom Anderson.', "correct_answer": "False"},
    {"question": "Daft Punk originated in France.", "correct_answer": "True"},
    {"question": "Sugar contains fat.", "correct_answer": "False"},
    {"question": 'The first Maxis game to feature the fictional language "Simlish" was The Sims (2000).', "correct_answer": "False"},
    {"question": "Martin Luther King Jr. and Anne Frank were born the same year.", "correct_answer": "True"},
    {"question": "Alaska is the largest state in the United States.", "correct_answer": "True"},
    {"question": "In 1993, Prince changed his name to an unpronounceable symbol because he was unhappy with his contract with Warner Bros.", "correct_answer": "True"},
    {"question": "Celiac Disease is a disease that affects the heart, causing those affected to be unable to eat meat.", "correct_answer": "False"},
    {"question": "There is a city called Rome in every continent on Earth.", "correct_answer": "False"},
    {"question": "The Ceratosaurus, a dinosaur known for having a horn on the top of its nose, is also known to be a descendant of the Tyrannosaurus Rex.", "correct_answer": "False"},
    {"question": 'There aren\'t any live-action clones in "Star Wars: Episode III - Revenge of the Sith".', "correct_answer": "True"},
    {"question": 'The singer Billie Holiday was also known as "Lady Day".', "correct_answer": "True"},
    {"question": "The 2016 United States Presidential Election is the first time Hillary Clinton has run for President.", "correct_answer": "False"},
    {"question": "When you cry in space, your tears stick to your face.", "correct_answer": "True"},
    {"question": "Nick Mason is the only member to appear on every Pink Floyd album.", "correct_answer": "True"},
    {"question": "Activision created Battlefield 1.", "correct_answer": "False"},
    {"question": 'There are 6 legendary cards in "Clash Royale".', "correct_answer": "False"},
    {"question": 'Waylon Smithers from "The Simpsons" was originally black when he first appeared in the series.', "correct_answer": "True"},
    {"question": '"I disapprove of what you say, but I will defend to the death your right to say it" is a quote from French philosopher Voltaire.', "correct_answer": "False"},
    {"question": "The shotgun appears in every numbered Resident Evil game.", "correct_answer": "True"},
    {"question": "Ana was added as a new hero for the game Overwatch on July 19th, 2016.", "correct_answer": "True"},
    {"question": "In Resident Evil 4, the Chicago Typewriter has infinite ammo.", "correct_answer": "True"},
    {"question": '"Resident Evil 7" is the first first-person Resident Evil game.', "correct_answer": "False"},
    {"question": "The open source program Redis is a relational database server.", "correct_answer": "False"},
    {"question": "Seoul is the capital of North Korea.", "correct_answer": "False"}
]
